### ISSUE TITLE
Thermostat support and program complexity

### ISSUE THREAD

**Issue by bubbzy** [echoromeo/hanobo#1]
Hi!

Sorry I posted on the wrong project, as mentioned I am new to a lot of this.

I would be happy to donate for this project to be a real and fully functioning component, how can we make that happened? 

Anyways, below is the issues I have noticed:
1. The current temperature of the thermostats is not showed anywhere in hass what I can see?
2. The nobø system can be set up with magnetic sensors on windows nearby that deactivates the heat if opened, I'm not sure if this is even possible via the API but it would be great if these were visible in HassIO as well.
3. The thermostats I HassIO shows two different temperatures, one which I think have no feature? I believe it is used on units with both heating and cooling but its confusing on these.
4. In the nobø app it seems to be possible to change to all the different scenes but the "normal". If you set the normal in nobøs app it does not use the mode "program", it goes to "eco".

/Erik

**Comment by echoromeo** [comment]
Hi @bubbzy,

1. Unfortunately I only have the R80-RDC 700 thermostat and that one does not support this feature. I do not like developing blind so either Someone™ should donate one to me or we need a developer on the team that has both Home Assistant and a more advanced thermostat.
2. [As mentioned ](https://github.com/echoromeo/pynobo/issues/12), this does not look available at the moment.
3. The two temperatures you see in Home-Assistant, those are the Comfort and Eco temperatures that the thermostat can be set to, and I agree this is not the best way to implement them in Home Assistant.
4. I made the component show the actual state instead of normal/program when no override is active. I think it would be beneficial to add override/program prefix to every state.

**Comment by bubbzy** [comment]
I have sic NCU-1R wich I'm not using. If they fit your radiators I would gladly donate the to you if the helps? @echoromeo 


![img_5023](https://user-images.githubusercontent.com/36682231/50741441-6b883f00-11fd-11e9-97ec-b56a4e009e70.jpg)
![img_3867](https://user-images.githubusercontent.com/36682231/50741442-6b883f00-11fd-11e9-97d7-7ea525251e49.jpg)
![img_1924](https://user-images.githubusercontent.com/36682231/50741443-6c20d580-11fd-11e9-8fce-c954a28823ab.jpg)

**Comment by echoromeo** [comment]
@bubbzy, sorry for the late reply. 
1. No, donating them will not help with this issue since [this post](https://www.hjemmeautomasjon.no/forums/topic/267-nob%C3%B8-energy-control/?do=findComment&comment=49281) says it is not possible. If you still want to give away one or more of your thermostats, send me an email on post alfakrøll undereksponert punktum no and we can work something out.
2. Still not supported
3. I will make a separate bug on this one.
4. You may have noticed, but I did a fix a while back to address this, what do you think?

**Comment by bubbzy** [comment]
Hi @echoromeo!

No problems, Im a little confused though, I am Swedish and lived I Oslo for a couple of years so my norwegian is ok but not flawless :)

Dosent Terje say that the temperature is possible to catch? I understood it that your thermostats didn't support that feature though and therefor I could donate the newer ones I have if it helps?

If it dosent help I can absolutely donate them anyway for the god job. I will send you an email.

**Comment by echoromeo** [comment]
Ah, sorry I did not think about the language. I usually code in english so then everything on github ended up in english.

Unfortunately, according to Terje the only temperatures that are available through the API are from the Nobø Switches. I implemented support for this in branch https://github.com/echoromeo/hanobo/tree/dev_zone_temperature, but I do not have any Nobø Switches to test it on.

**Comment by bubbzy** [comment]
Ah, now I understand :) The temperature available in the API is only the sensors in nobø wall switches? Like the one attached?  (I don't have or want those either) That Is to bad, was the guy you spoke to working for glen dimplex or just someone with good knowledge about the products? One would thing that it wouldn't be impossible for them to make it possible through the API, obviously in the thermostats there is a temp sensor so can't be to much work. Anyways that's not your fault :) 

![img_0768](https://user-images.githubusercontent.com/36682231/52970754-474f7e80-33b5-11e9-976f-aa831898758a.PNG)

**Comment by kknishev** [comment]
Hello @echoromeo 
Thank you so much for a absolutely useful plugin.
Sorry, I am not a developer, but only one adding from API manual about 'Y02':

> Component temperature value sent as part of a G00 response, or pushed from the Hub automatically to all connected clients whenever the Hub has received updated temperature data.

"all connected clients" - is it means that Hub know the current temp of all clients, not only Nobo Switches?! and is it possible to parsing G00 response? :/

Hope to buy Nobo Switch soon and test your lastest build.

**Comment by echoromeo** [comment]
Hi @KKnishev, no I am pretty sure the client in this case is just the user of the API, so Home Assistant or the mobile app.

**Comment by nesa05** [comment]
Hi @echoromeo, are you still have CU-1R, while I will need it and it is currently impossible to buy it anywhere?

**Comment by NoKeRse** [comment]
@nesa05 If you are in Norway take alook at Eldirekte [https://www.eldirekte.no/search?kw=Ncu](https://www.eldirekte.no/search?kw=Ncu) 
[https://www.eldirekte.no/search?kw=Dcu] (https://www.eldirekte.no/search?kw=Dcu) 
They have both the Dimplex and NOBO series :)

**Comment by echoromeo** [comment]
@nesa05, sure, I have 3 I can send you :)

**Comment by nesa05** [comment]
Txh a lot…can you sent it to Germany, Berlin, I will pay shipping costs.

Best regards
n

**Comment by echoromeo** [comment]
Ah, that makes it a bit more complicated. Send me an email, you can find the address further up.

**Comment by nesa05** [comment]
My email

nerman.ceho@
gmail.com
