### ISSUE TITLE
Add override type selection

### ISSUE THREAD

**Issue by gregersn** [echoromeo/hanobo#14]
Sometime before the update February 28th, it was possible to change from e.g. Comfort to Eco, and still be in auto mode, so that next time the auto schedule would then change to Comfort, it would go back to that. 

With the latest version, it seems that if I try to change from Comfort to Eco, or anything, it also switches from Auto to Heat, and stays there until I manually change it back.

**Comment by echoromeo** [comment]
Hi, this is due to a change on [line 187](https://github.com/echoromeo/hanobo/blob/ac8770450c64c22b4a01ce2394a6fc7a03823fea/climate.py#L187) in climate.py. A permanent override allows a more consistent user experience for those who wants HA to control everything.

You can change it back by replacing OVERRIDE_TYPE_CONSTANT with OVERRIDE_TYPE_NOW on that line.

We should add an option to select override type in HA, I will rename this issue and keep it open.

**Comment by oyvindwe** [comment]
Configuration option added in https://github.com/home-assistant/core/pull/50913
