### ISSUE TITLE
Global override

### ISSUE THREAD

**Issue by Gadget111** [echoromeo/hanobo#17]
Would it be possible to have a global override? This would in effect replicate the 4 main buttons on the app.

I love this code. I was previously using MQTT to send heater controls to an interface I had written (running on an ESP8266), but this is much better.. Many many thanks for all your work.

**Comment by echoromeo** [comment]
Hi @Gadget111, yes it should be possible, but I am not sure how much work it is.

Have you tried grouping the zones together? https://www.home-assistant.io/integrations/group/
That should hopefully work, and is an easy workaround before it gets added to the code

**Comment by swaner** [comment]
+1 for this feature. I tried grouping zones but for my use case, it has some unwanted side effects.

1. I usually set some rooms I do not use to "away"
2. When armed I set all the zones to "eco"
3. When unarmed I set all the zones back to "auto"

This causes all the zones to be resetted back to auto, if I could use a "global" override it would not affect my rooms set to "away".

Thanks for an excellent plugin otherwise 👍

**Comment by oyvindwe** [comment]
@echoromeo How do you think it could be done? Adding an extra "global" climate component that's not connected to zone?

**Comment by oyvindwe** [comment]
I am working on a change to the official integration that supports changing week profile for zones and global override:
https://github.com/oyvindwe/home-assistant/tree/nobo_hub-profiles

It simply uses `select` entities for this, so the UI won't be very fancy.

**Comment by oyvindwe** [comment]
This has been submitted a while ago, but is still awaiting review: https://github.com/home-assistant/core/pull/80866

**Comment by echoromeo** [comment]
Archiving repo, closing issue
