### ISSUE TITLE
Support for Dimplex Alta heaters

### ISSUE THREAD

**Issue by jonaskul** [echoromeo/hanobo#36]
Hello. Just tried to connect this to a Dimplex heater. No luck. Read a little further that the Nobø heats may not share any of the technology even though it is the same company.

Do you know if there is any way to use your integration with Dimplex? They use the Dimplex Capa app.
https://dimplex.no/dimplex-alta

**Comment by NoKeRse** [comment]
The Dimplex Alta heaters are WIFI based and controlled directly via WIFI. And those heaters can't be added to the Energy Control Hub. Since communication between HUB and heaters is over 868 MHz

So the hanobo solution won't work for the Alta Heaters I'm afraid.

Since I don't own one of the Alta heaters,.Invested in new ones a month before they released them...

What can be done, is to send GlenDimplex main office  an email asking if there is any OpenAPI with documentation that is available, or if they have any plans to releasing any. 
And refer to this project for instance. Aswell as to the [OpenAPI documentation on GlenDimplex.no for Energy Control]\(https://www.glendimplex.no/produkter/varmestyring/11123610/noboe-hub/c-77/p-330)
The Dimplex brand is what I can understand the more international variant for GlenDimplex. So my bet is that if they are enlightened in the potential that HomeAssistant and smarthome can give them :) 

I see on the norwegian facebook page that there where some request regarding NOBØ and Dimplex heaters and integration to Athom Homey,  but those requests is 3 years old and at that time they said there were no plans. But a lot of water have been flowing in the river since then :)

**Comment by jonaskul** [comment]
Thank you! I will try to contact them directly or go through Elektroimportøren.

**Comment by echoromeo** [comment]
@jonaskul, I sent an email to Nobø every year to ask about releasing the API. I doubt my nagging was the main reason, but finally the legendary employee Terje sent me an email saying he was able to convince management that they should release the API. Unfortunately, Terje left Dimplex to pursue other interests..
Soo, send them emails!

**Comment by jorgeb1502** [comment]
Any news about this?

**Comment by jonaskul** [comment]
> Any news about this?

I got in touch with product owner in Norway, but he could not do anything but agree to that they are behind on openness and have to push on their applications department.
