### ISSUE TITLE
`Platform not found: climate.nobo_hub` when trying to install

### ISSUE THREAD

**Issue by charlietomo** [echoromeo/hanobo#6]
I am having an issue whereby I cannot even load `climate.nobo_hub` and I get the error 

```
Platform not found: climate.nobo_hub
9:22 PM components/hassio/__init__.py (ERROR) - message first occured at 7:22 PM and shows up 5 times
```

I have all the downloaded files in `/config/custom_components/nobo_hub`.

I see references to needing `_init_.py` (and the reference again in my error), breaking changes for custom components in ~0.90 release and mention of the files needing the correct permissions.

Should this work with the latest 0.94.x version of Home Assistant? Is there anything specific that needs to be done for it to work with Hass.io? Am I missing an `__init__.py` ?

I am really excited to try this out as my new Nobo heaters are the only thing not integrated with HA in my setup!

**Comment by echoromeo** [comment]
Hi, great issue description, but I think you are missing the full error message.
Can you try to get the full message? Either by clicking it in the UI (where you probably copied it from) or directly from home_assistant.log.

And the most likely culprit: Did you download the pynobo folder inside the nobo_hub folder?
I tested it this weekend with 0.94 so that should be ok. I am running home assistant from docker, not hass.io, but I do not think that should be a problem.

**Comment by charlietomo** [comment]
I downloaded using git clone and had a `pynobo` folder in the correct place. However on closer inspection it was empty! A quick download of the zip and copy the files into the right place, and now it loads as I initially expected! Many thanks for the pointer.

Will close this now. Might be worth a note on the readme.
